# Generated by Django 5.0.1 on 2024-02-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
