# Generated by Django 5.0.1 on 2024-01-31 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('hiredate', models.DateTimeField(default=datetime.datetime.now)),
                ('sal', models.IntegerField(default=0)),
            ],
        ),
    ]
